In [ ]:
import matplotlib.pyplot as plt
import pandas      as pd
import numpy       as np
import seaborn as sns
import sklearn

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [ ]:
h1bdf = pd.read_csv(r'/content/gdrive/My Drive/H1B Dataset2.csv', encoding='ISO-8859-1')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (25) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
h1bdf.shape

(528134, 27)

In [ ]:
h1bdf.dropna(inplace=True)

In [ ]:
h1bdf.shape

(517745, 27)

In [ ]:
h1bdf.VISA_CLASS.value_counts()

H1B               517265
E3 Australian        363
H1B1 Singapore        61
H1B1 Chile            56
Name: VISA_CLASS, dtype: int64

In [ ]:
h1bdf.SOC_NAME.value_counts()

COMPUTER OCCUPATION                  240883
ANALYSTS                             110624
ENGINEERS                             43373
SCIENTIST                             17440
FINANCE                               12934
DOCTORS                               12750
EDUCATION                             12088
ACCOUNTANTS                           10530
MARKETING                             10393
IT MANAGERS                            6008
MANAGERS                               5035
MATHEMATICIANS AND STATISTICIANS       4951
HUMAN RESOURCES                        3055
ARCHITECTURE                           2336
LAWYERS AND LEGAL SUPPORT WORKERS      2180
DESIGNERS                              2019
LAB TECHNICIANS                        2003
GRAPHIC DESIGNERS                      1959
LOGISTICIANS                           1738
HEALTHCARE                             1683
INTERNIST                              1492
PUBLIC RELATIONS                       1089
BUSINESS OPERATIONS SPECIALIST  

In [ ]:
indexNames = h1bdf[h1bdf['VISA_CLASS'] == 'E3 Australian'].index
indexNames

Int64Index([  2904,   3125,   3812,   4010,   4063,   4065,   4338,   4690,
              5028,   5536,
            ...
            521790, 521794, 522487, 523440, 524108, 524135, 526570, 527052,
            527583, 527982],
           dtype='int64', length=363)

In [ ]:
h1bdf.drop(indexNames , inplace=True)


In [ ]:
indexNames = h1bdf[h1bdf['VISA_CLASS'] == 'H1B1 Singapore'].index
indexNames

Int64Index([  7302,   8510,  32551,  51778,  54250,  54251,  55352,  56249,
             65388,  68023,  72225,  78169,  89423,  97101,  98352, 105594,
            108785, 109112, 111750, 112293, 113358, 113359, 117004, 119736,
            121892, 123153, 123852, 145276, 151317, 155350, 213303, 213343,
            230793, 240011, 341743, 344970, 346390, 354317, 400052, 409631,
            415925, 422704, 429784, 437673, 440482, 450386, 460178, 479379,
            481959, 483083, 483939, 490840, 494421, 496690, 497845, 500312,
            501449, 516290, 516482, 516498, 525801],
           dtype='int64')

In [ ]:
h1bdf.drop(indexNames , inplace=True)


In [ ]:
indexNames = h1bdf[h1bdf['VISA_CLASS'] == 'H1B1 Chile'].index
indexNames

Int64Index([  6708,   7080,   8291,  16256,  19881,  23063,  28763,  29265,
             30599,  36228,  49710,  54623,  55036,  60849,  68928,  77181,
             89623,  93644,  93645,  94399, 104395, 106191, 112779, 114926,
            123594, 129805, 136010, 138868, 139523, 152213, 207527, 211339,
            229131, 301915, 342907, 379190, 379191, 405475, 414544, 418530,
            420643, 421577, 429036, 456477, 457791, 466290, 472153, 481515,
            483555, 483581, 486440, 490225, 491440, 492720, 506686, 521974],
           dtype='int64')

In [ ]:
h1bdf.drop(indexNames , inplace=True)


In [ ]:
h1bdf.shape

(517265, 27)

In [ ]:
h1bdf['FULL_TIME_POSITION'] = h1bdf['FULL_TIME_POSITION'].replace(['Y'],1)
h1bdf['FULL_TIME_POSITION'] = h1bdf['FULL_TIME_POSITION'].replace(['N'],0)
#h1bdf.head()
h1bdf.FULL_TIME_POSITION.value_counts()

1    505467
0     11798
Name: FULL_TIME_POSITION, dtype: int64

In [ ]:
h1bdf['WILLFUL_VIOLATOR'] = h1bdf['WILLFUL_VIOLATOR'].replace(['Y'],1)
h1bdf['WILLFUL_VIOLATOR'] = h1bdf['WILLFUL_VIOLATOR'].replace(['N'],0)
#h1bdf.head()
h1bdf.WILLFUL_VIOLATOR.value_counts()

0    516846
1       419
Name: WILLFUL_VIOLATOR, dtype: int64

In [ ]:
h1bdf['H-1B_DEPENDENT'] = h1bdf['H-1B_DEPENDENT'].replace(['Y'],1)
h1bdf['H-1B_DEPENDENT'] = h1bdf['H-1B_DEPENDENT'].replace(['N'],0)
h1bdf.head(2)
#h1bdf.H-1B_DEPENDENT.value_counts()

CASE_SUBMITTED_DAY  ...         CASE_STATUS
0                  24  ...  CERTIFIEDWITHDRAWN
1                   4  ...  CERTIFIEDWITHDRAWN

[2 rows x 27 columns]

In [ ]:
h1bdf.CASE_STATUS.value_counts()

CERTIFIED             459833
CERTIFIEDWITHDRAWN     35559
WITHDRAWN              15685
DENIED                  6188
Name: CASE_STATUS, dtype: int64

In [ ]:
print("certified instances : ",count_C)
print("certified withdrawn instances : ",count_CW)
print("withdrawn instances : ",count_W)
print("denied instances : ",count_D)

NameError: ignored

In [ ]:
h1bdf_C = h1bdf[h1bdf['CASE_STATUS'] == 'CERTIFIED']

In [ ]:
h1bdf_C.shape

(459833, 27)

In [ ]:
from sklearn.utils import resample

h1bdf_C_downsampled = resample(h1bdf_C,replace=False,n_samples=50000,random_state=123)                                   
h1bdf_C_downsampled.shape

(50000, 27)

In [ ]:
h1bdf_NotCertified = h1bdf[h1bdf['CASE_STATUS'] != 'CERTIFIED']

In [ ]:
h1bdf_NotCertified.CASE_STATUS.value_counts()

CERTIFIEDWITHDRAWN    35559
WITHDRAWN             15685
DENIED                 6188
Name: CASE_STATUS, dtype: int64

In [ ]:
h1bdf_sampled = pd.concat([h1bdf_NotCertified,h1bdf_C_downsampled],ignore_index=True)

In [ ]:
h1bdf_sampled.CASE_STATUS.value_counts()

CERTIFIED             50000
CERTIFIEDWITHDRAWN    35559
WITHDRAWN             15685
DENIED                 6188
Name: CASE_STATUS, dtype: int64

In [ ]:
X= h1bdf_sampled.iloc[:,:-1].values
y= h1bdf_sampled.iloc[:,-1].values

In [ ]:
y

array(['CERTIFIEDWITHDRAWN', 'CERTIFIEDWITHDRAWN', 'CERTIFIEDWITHDRAWN',
       ..., 'CERTIFIED', 'CERTIFIED', 'CERTIFIED'], dtype=object)

In [ ]:
y.shape

(107432,)

In [ ]:
from sklearn import preprocessing
lab_encode = preprocessing.LabelEncoder()
lab_encode.fit(y)
list(lab_encode.classes_)
y1 = lab_encode.transform(y)

In [ ]:
y1

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
y1.shape

(107432,)

In [ ]:
#cdf_class_c = cdf[cdf.CASE_STATUS=='CERTIFIED']
#cdf_class_d = cdf[cdf.CASE_STATUS=='DENIED']

In [ ]:
col_array = ['CASE_SUBMITTED_YEAR','EMPLOYER_NAME','EMPLOYER_STATE','SOC_NAME','FULL_TIME_POSITION','PREVAILING_WAGE','PW_SOURCE','WAGE_RATE_OF_PAY_FROM']

In [ ]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
numh1bdf = h1bdf_sampled.select_dtypes(include=numerics)
X_num = numh1bdf.to_numpy()

In [ ]:
X_num

array([[2.40000e+01, 2.00000e+00, 2.01600e+03, ..., 6.73200e+04,
        0.00000e+00, 0.00000e+00],
       [4.00000e+00, 3.00000e+00, 2.01600e+03, ..., 5.72000e+04,
        0.00000e+00, 0.00000e+00],
       [1.00000e+01, 3.00000e+00, 2.01600e+03, ..., 0.00000e+00,
        1.00000e+00, 0.00000e+00],
       ...,
       [2.00000e+00, 2.00000e+00, 2.01700e+03, ..., 1.36652e+05,
        0.00000e+00, 0.00000e+00],
       [2.50000e+01, 4.00000e+00, 2.01700e+03, ..., 9.55000e+04,
        1.00000e+00, 0.00000e+00],
       [1.70000e+01, 1.00000e+00, 2.01700e+03, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [ ]:
X_num.shape

(107432, 15)

In [ ]:
objh1bdf = h1bdf_sampled.select_dtypes(include=['object']).drop(["WORKSITE_POSTAL_CODE", "EMPLOYER_NAME", "EMPLOYER_COUNTRY", "WAGE_UNIT_OF_PAY", "PW_UNIT_OF_PAY","VISA_CLASS"], axis=1)
objh1bdf.head(2)

EMPLOYER_STATE  SOC_NAME  ... WORKSITE_STATE         CASE_STATUS
0             IL  ANALYSTS  ...             IL  CERTIFIEDWITHDRAWN
1             IL  ANALYSTS  ...             IL  CERTIFIEDWITHDRAWN

[2 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
X_cat = enc.fit_transform([[x,y,z,w,p] for x,y,z,w,p in zip(objh1bdf['EMPLOYER_STATE'], objh1bdf['SOC_NAME'], objh1bdf['PW_SOURCE'], objh1bdf['PW_SOURCE_OTHER'],objh1bdf['WORKSITE_STATE'])]).toarray()
X_cat

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_cat.shape

(107432, 340)

In [ ]:
X = np.hstack((X_num,X_cat))
X

array([[2.400e+01, 2.000e+00, 2.016e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [4.000e+00, 3.000e+00, 2.016e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+01, 3.000e+00, 2.016e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.000e+00, 2.000e+00, 2.017e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.500e+01, 4.000e+00, 2.017e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.700e+01, 1.000e+00, 2.017e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [ ]:
X.shape

(107432, 355)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scale = scaler.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scale,y1, test_size = 0.15, random_state = 101)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_train,y_train, test_size = 0.2, random_state = 101)

In [ ]:
from sklearn.linear_model import LogisticRegression
h1b_logreg = LogisticRegression(multi_class='ovr')
h1b_logreg

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
h1b_logreg.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
pred = h1b_logreg.predict(X_test)
pred

array([0, 0, 2, ..., 0, 3, 0])

In [ ]:
pred_v = h1b_logreg.predict(X_val)
pred_v

array([1, 0, 0, ..., 3, 0, 1])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      7491
           1       0.85      0.89      0.87      5287
           2       0.62      0.21      0.31       956
           3       0.69      0.64      0.67      2381

    accuracy                           0.81     16115
   macro avg       0.75      0.66      0.68     16115
weighted avg       0.80      0.81      0.80     16115



In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_val,pred_v))

              precision    recall  f1-score   support

           0       0.82      0.89      0.86      8441
           1       0.85      0.89      0.87      6078
           2       0.65      0.21      0.32      1070
           3       0.71      0.63      0.67      2675

    accuracy                           0.81     18264
   macro avg       0.76      0.66      0.68     18264
weighted avg       0.81      0.81      0.80     18264



In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[6710,  493,   57,  231],
       [ 486, 4696,    7,   98],
       [ 387,   26,  197,  346],
       [ 499,  301,   56, 1525]])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val,pred_v)

array([[7549,  609,   47,  236],
       [ 548, 5419,    7,  104],
       [ 443,   52,  227,  348],
       [ 611,  309,   67, 1688]])

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)

0.7046850760161341

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_val, pred_v)

0.7044459045116075

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, pred, average='macro')

0.6766086577115197

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_val, pred_v, average='macro')

0.6790294523995635

In [ ]:
from sklearn import metrics
fpr, tpr, thresholds = metrics.roc_curve(y_test, pred, pos_label=2)
metrics.auc(fpr, tpr)

0.6413163769482813

In [ ]:
from sklearn import metrics
fpr_v, tpr_v, thresholds_v = metrics.roc_curve(y_val, pred_v, pos_label=2)
metrics.auc(fpr_v, tpr_v)

0.6308432141618627

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.8146447409246044

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, pred_v)

0.8148817345597897

In [ ]:
from sklearn.linear_model import LogisticRegression
h1b_logreg1 = LogisticRegression(multi_class='multinomial')
h1b_logreg1

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
h1b_logreg1.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
pred1 = h1b_logreg1.predict(X_test)
pred1

array([0, 0, 2, ..., 0, 3, 0])

In [ ]:
pred1_v = h1b_logreg1.predict(X_val)
pred1_v

array([1, 0, 0, ..., 3, 0, 1])

In [ ]:
pred1_v_log_prob = h1b_logreg1.predict_log_proba(X_val)
pred1_v_log_prob.shape

(18264, 4)

In [ ]:
pred1_v_prob = h1b_logreg1.predict_proba(X_val)
pred1_v_prob

array([[0.35572696, 0.6101332 , 0.00760042, 0.02653942],
       [0.92436785, 0.02948889, 0.01403264, 0.03211063],
       [0.9374729 , 0.02989042, 0.01028504, 0.02235163],
       ...,
       [0.07080814, 0.05304318, 0.10378142, 0.77236726],
       [0.62676388, 0.03089122, 0.16840838, 0.17393652],
       [0.13988089, 0.82489012, 0.00749099, 0.027738  ]])

In [ ]:
maxarray_v = np.amax(pred1_v_prob,axis=1)

In [ ]:
indexarray_v = np.argmax(pred1_v_prob,axis=1)

In [ ]:
np.unique(indexarray_v)

array([0, 1, 2, 3])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred1))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      7491
           1       0.87      0.87      0.87      5287
           2       0.57      0.24      0.34       956
           3       0.69      0.64      0.66      2381

    accuracy                           0.82     16115
   macro avg       0.74      0.67      0.69     16115
weighted avg       0.81      0.82      0.81     16115



In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_val,pred1_v))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      8441
           1       0.87      0.88      0.88      6078
           2       0.62      0.25      0.36      1070
           3       0.71      0.63      0.66      2675

    accuracy                           0.82     18264
   macro avg       0.76      0.67      0.69     18264
weighted avg       0.81      0.82      0.81     18264



In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred1)

array([[6806,  374,   84,  227],
       [ 526, 4613,    7,  141],
       [ 375,   17,  230,  334],
       [ 482,  286,   84, 1529]])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val,pred1_v)

array([[7719,  438,   59,  225],
       [ 588, 5345,    7,  138],
       [ 436,   28,  266,  340],
       [ 598,  300,   96, 1681]])

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred1)

0.699162271175923

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_val, pred1_v)

0.6918528252299606

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, pred1, average='macro')

0.6853554861617333

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_val, pred1_v, average='macro')

0.6912249927784235

In [ ]:
from sklearn import metrics
fpr1, tpr1, thresholds1 = metrics.roc_curve(y_test, pred1, pos_label=2)
metrics.auc(fpr1, tpr1)

0.649960178040249

In [ ]:
from sklearn import metrics
fpr1_v, tpr1_v, thresholds1_v = metrics.roc_curve(y_val, pred1_v, pos_label=2)
metrics.auc(fpr1_v, tpr1_v)

0.6404443410492032

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred1)

0.8177474402730376

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, pred1_v)

0.8218900569426194

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test, pred1, average='macro')

0.7390954311714748

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_val, pred1_v, average='macro')

0.7569054910681504

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, pred1, average='macro')

0.6659568403620939

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_val, pred1_v, average='macro')

0.6677188938380835

In [ ]:
from sklearn.linear_model import SGDClassifier
h1b_SGD = SGDClassifier()
h1b_SGD

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
h1b_SGD.fit(X_train,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
pred2 = h1b_SGD.predict(X_test)
pred2

array([0, 0, 2, ..., 0, 3, 0])

In [ ]:
pred2_v = h1b_SGD.predict(X_val)
pred2_v

array([1, 0, 0, ..., 3, 0, 1])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84      7491
           1       0.79      0.92      0.85      5287
           2       0.56      0.19      0.28       956
           3       0.72      0.62      0.67      2381

    accuracy                           0.80     16115
   macro avg       0.73      0.64      0.66     16115
weighted avg       0.79      0.80      0.78     16115



In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_val,pred2_v))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84      8441
           1       0.79      0.92      0.85      6078
           2       0.58      0.20      0.29      1070
           3       0.73      0.60      0.66      2675

    accuracy                           0.80     18264
   macro avg       0.73      0.64      0.66     18264
weighted avg       0.79      0.80      0.78     18264



In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred2)

array([[6335,  904,   84,  168],
       [ 370, 4848,   12,   57],
       [ 357,   65,  183,  351],
       [ 538,  309,   50, 1484]])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val,pred2_v)

array([[7149, 1048,   71,  173],
       [ 401, 5604,   10,   63],
       [ 406,   99,  209,  356],
       [ 669,  330,   69, 1607]])

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred2)

0.7033198883028234

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_val, pred2_v)

0.7140275952693824

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, pred2, average='macro')

0.6605684067097233

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_val, pred2_v, average='macro')

0.6603680452849593

In [ ]:
from sklearn import metrics
fpr2, tpr2, thresholds2 = metrics.roc_curve(y_test, pred2, pos_label=2)
metrics.auc(fpr2, tpr2)

0.650670776795259

In [ ]:
from sklearn import metrics
fpr2_v, tpr2_v, thresholds2_v = metrics.roc_curve(y_val, pred2_v, pos_label=2)
metrics.auc(fpr2_v, tpr2_v)

0.6421192896022194

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred2)

0.7973937325473162

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, pred2_v)

0.7976894437144109

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test, pred2, average='macro')

0.725388245788398

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_val, pred2_v, average='macro')

0.7333106576362797

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, pred2, average='macro')

0.6443344391525255

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_val, pred2_v, average='macro')

0.6412565383324502

In [ ]:
from sklearn.linear_model import SGDClassifier
h1b_SGD1 = SGDClassifier(loss='log')
h1b_SGD1

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
h1b_SGD1.fit(X_train,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
pred3 = h1b_SGD1.predict(X_val)
pred3

array([1, 0, 0, ..., 3, 0, 1])

In [ ]:
pred3_prob = h1b_SGD1.predict_proba(X_test)
pred3_prob

array([[0.92384671, 0.03513522, 0.0094548 , 0.03156328],
       [0.90299196, 0.00605776, 0.03863768, 0.05231259],
       [0.06753101, 0.51693072, 0.39977378, 0.01576449],
       ...,
       [0.75163485, 0.02272104, 0.20856496, 0.01707915],
       [0.0644937 , 0.06401092, 0.05364422, 0.81785116],
       [0.45935556, 0.00240154, 0.20216048, 0.33608242]])

In [ ]:
#indexarray = np.argmax(pred1_prob,axis=1)

In [ ]:
#np.unique(indexarray)

In [ ]:
#from sklearn.metrics import classification_report
#print(classification_report(y_val,pred3))

In [ ]:
#from sklearn.metrics import confusion_matrix
#confusion_matrix(y_val,pred3)

In [ ]:
#from sklearn.metrics import mean_squared_error
#mean_squared_error(y_val, pred3)

In [ ]:
#from sklearn.metrics import f1_score
#f1_score(y_val, pred3, average='macro')

In [ ]:
#from sklearn import metrics
#fpr3, tpr3, thresholds3 = metrics.roc_curve(y_val, pred3, pos_label=2)
#metrics.auc(fpr3, tpr3)

In [ ]:
#from sklearn.metrics import accuracy_score
#accuracy_score(y_val, pred3)

In [ ]:
#from sklearn.metrics import recall_score
#recall_score(y_val, pred3, average='macro')

In [ ]:
#from sklearn.metrics import precision_score
#precision_score(y_val, pred3, average='macro')

# New Section

In [ ]:
#from sklearn.tree import DecisionTreeClassifier

#from sklearn.tree import export_graphviz

#from sklearn.tree import export_text

#from sklearn import tree

#from IPython.display import Image

 

#dt = tree.DecisionTreeClassifier() #create model

#fig, ax = plt.subplots(figsize=(14, 14))

#tree.plot_tree(dt.fit(X_train, y_train), max_depth=4, fontsize=10,filled=True) #train model

#plt.show()

In [ ]:
#y_pred = dt.predict(X_test)

 

#y_prob = dt.predict_proba(X_test)

 

#print("test", y_test[:10])

#print("pred", y_pred[:10])

#print()

 

#print(confusion_matrix(y_test,y_pred))

#print(classification_report(y_test, y_pred))

In [ ]:
#y_pred2 = dt.predict(X_val)
#y_prob = dt.predict_proba(X_val)
#print("test", y_val[:10])
#print("pred", y_pred2[:10])
#print()

#print(confusion_matrix(y_val,y_pred2))
#print(classification_report(y_val, y_pred2))

In [ ]:
#from sklearn.metrics import accuracy_score

#accuracy_score(y_val, y_pred2)

In [ ]:
#y_val.shape

In [ ]:
#y_test.shape

In [ ]:
#y_pred.shape

In [ ]:
#from sklearn.metrics import accuracy_score

#accuracy_score(y_val, y_pred2)

In [ ]:
#from sklearn.metrics import mean_squared_error
#mean_squared_error(y_test, y_pred)

In [ ]:
#from sklearn.metrics import mean_squared_error
#mean_squared_error(y_val, y_pred2)

In [ ]:
#from sklearn import metrics

#fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=2)

#metrics.auc(fpr, tpr)

In [ ]:
#from sklearn import metrics

#fprdv, tprdv, thresholdsdv = metrics.roc_curve(y_val,y_pred2, pos_label=2)

#metrics.auc(fprdv, tprdv)

In [ ]:
#from sklearn.metrics import f1_score

#f1_score(y_test, y_pred, average='macro')

In [ ]:
#from sklearn.metrics import f1_score

#f1_score(y_val, y_pred2, average='macro')

In [ ]:
#from sklearn.metrics import precision_score

#precision_score(y_test, y_pred, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

In [ ]:
#from sklearn.metrics import precision_score

#precision_score(y_val, y_pred2, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

In [ ]:
#from sklearn.metrics import recall_score

#recall_score(y_test, y_pred, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

In [ ]:
#from sklearn.metrics import recall_score

#recall_score(y_val, y_pred2, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

In [ ]:
from sklearn.ensemble import RandomForestClassifier # <- Random Forest Classifier

In [ ]:
rf = RandomForestClassifier(n_estimators = 75, random_state = 50) #Build (no. of estimators can be increased)
# Train the model on training data
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=75,
                       n_jobs=None, oob_score=False, random_state=50, verbose=0,
                       warm_start=False)

In [ ]:
y_pred_rf =  rf.predict(X_val) #Predict
probs = rf.predict_proba(X_val)

print("test", y_val[:10])
print("pred", y_pred_rf[:10])
print(confusion_matrix(y_val,y_pred_rf))
print(classification_report(y_val, y_pred_rf))

test [1 0 0 1 3 1 0 1 0 0]
pred [1 0 0 1 3 1 0 1 0 0]
[[8163  152   27   99]
 [ 274 5776    2   26]
 [ 436   31  300  303]
 [ 449  196   87 1943]]
              precision    recall  f1-score   support

           0       0.88      0.97      0.92      8441
           1       0.94      0.95      0.94      6078
           2       0.72      0.28      0.40      1070
           3       0.82      0.73      0.77      2675

    accuracy                           0.89     18264
   macro avg       0.84      0.73      0.76     18264
weighted avg       0.88      0.89      0.88     18264



In [ ]:
y_pred_rf2 =  rf.predict(X_test) #Predict
probs = rf.predict_proba(X_test)

print("test", y_test[:10])
print("pred", y_pred_rf2[:10])
print(confusion_matrix(y_test,y_pred_rf2))
print(classification_report(y_test, y_pred_rf2))

test [0 0 1 1 1 1 2 1 0 0]
pred [0 0 1 1 1 0 0 0 0 0]
[[7213  147   36   95]
 [ 254 5015    5   13]
 [ 384    9  269  294]
 [ 384  169   65 1763]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      7491
           1       0.94      0.95      0.94      5287
           2       0.72      0.28      0.40       956
           3       0.81      0.74      0.78      2381

    accuracy                           0.88     16115
   macro avg       0.84      0.73      0.76     16115
weighted avg       0.88      0.88      0.87     16115



In [ ]:
#from sklearn.metrics import mean_squared_error
#mean_squared_error(y_val, y_pred_rf)

0.46654621112571176

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred_rf2)

0.4649705243561899

In [ ]:
#from sklearn import metrics
#fpr, tpr, thresholds = metrics.roc_curve(y_val, y_pred_rf, pos_label=2)
#metrics.auc(fpr, tpr)

0.6372803379574923

In [ ]:
from sklearn import metrics
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred_rf2, pos_label=2)
metrics.auc(fpr, tpr)

0.6447669004231574

In [ ]:
#from sklearn.metrics import f1_score
#f1_score(y_val, y_pred_rf, average='macro')

0.7593289649772172

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred_rf2, average='macro')

0.760247744433787

In [ ]:
#from sklearn.metrics import accuracy_score
#accuracy_score(y_val, y_pred_rf)

0.8860052562417872

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_rf2)

0.8848898541731306

In [ ]:
#from sklearn.metrics import precision_score
#precision_score(y_val, y_pred_rf, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

0.8386834494515897

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred_rf2, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

0.8366715461271663

In [ ]:
#from sklearn.metrics import recall_score
#recall_score(y_val, y_pred_rf, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

0.7310267720893096

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred_rf2, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

0.7333169496974595

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import metrics

In [ ]:
#gb = GradientBoostingClassifier(n_estimators = 75, random_state = 50)
#gb.fit(X_train, y_train)

In [ ]:
#y_pred_gb = gb.predict(X_val)
#gb_probs = gb.predict_proba(X_val)

#print("test", y_val[:10])
#print("pred", y_pred_gb[:10])
#print(confusion_matrix(y_val,y_pred_gb))
#print(classification_report(y_val, y_pred_gb))

In [ ]:
#from sklearn.metrics import mean_squared_error
#mean_squared_error(y_val, y_pred_gb)

In [ ]:
#from sklearn import metrics
#fpr, tpr, thresholds = metrics.roc_curve(y_val, y_pred_gb, pos_label=2)
#metrics.auc(fpr, tpr)

In [ ]:
#from sklearn.metrics import f1_score
#f1_score(y_val, y_pred_gb, average='macro')

In [ ]:
#from sklearn.metrics import accuracy_score
#accuracy_score(y_val, y_pred_gb)

In [ ]:
#from sklearn.metrics import precision_score
#precision_score(y_val, y_pred_gb, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')


In [ ]:
#from sklearn.metrics import recall_score
#recall_score(y_val, y_pred_gb, labels=None, pos_label=1, average='macro', sample_weight=None, zero_division='warn')

In [ ]:
#from sklearn.svm import SVC

#svm_clf = SVC(gamma="auto")
#svm_clf.fit(X_train, y_train)

In [ ]:
#y_pred_sv =  svm_clf.predict(X_val) #Predict

#print("test", y_val[:10])
#print("pred", y_pred_sv[:10])
#print(confusion_matrix(y_val,y_pred_sv))
#print(classification_report(y_val, y_pred_sv))