<a href="https://colab.research.google.com/github/Promodinivenkatakrishnan/python-notebooks/blob/main/WhiteWine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as mp
import sklearn
import seaborn as sb

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving wineQualityWhites.csv to wineQualityWhites (1).csv


In [ ]:
import io
whitewinedf = pd.read_csv(io.BytesIO(uploaded['wineQualityWhites.csv']))

In [ ]:
whitewinedf['New_Quality'] = whitewinedf['quality']

In [ ]:
whitewinedf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            4898 non-null   int64  
 1   fixed.acidity         4898 non-null   float64
 2   volatile.acidity      4898 non-null   float64
 3   citric.acid           4898 non-null   float64
 4   residual.sugar        4898 non-null   float64
 5   chlorides             4898 non-null   float64
 6   free.sulfur.dioxide   4898 non-null   float64
 7   total.sulfur.dioxide  4898 non-null   float64
 8   density               4898 non-null   float64
 9   pH                    4898 non-null   float64
 10  sulphates             4898 non-null   float64
 11  alcohol               4898 non-null   float64
 12  quality               4898 non-null   int64  
 13  New_Quality           4898 non-null   int64  
dtypes: float64(11), int64(3)
memory usage: 535.8 KB


In [ ]:
New_Quality=pd.cut(whitewinedf['quality'], bins=[3, 7, 9], include_lowest=True, labels=['worst', 'best'])

In [ ]:
whitewinedf['New_Quality']=New_Quality

In [ ]:
whitewinedf.head()

Unnamed: 0  fixed.acidity  volatile.acidity  ...  alcohol  quality  New_Quality
0           1            7.0              0.27  ...      8.8        6        worst
1           2            6.3              0.30  ...      9.5        6        worst
2           3            8.1              0.28  ...     10.1        6        worst
3           4            7.2              0.23  ...      9.9        6        worst
4           5            7.2              0.23  ...      9.9        6        worst

[5 rows x 14 columns]

In [ ]:
whitewinedf1 = whitewinedf.drop("Unnamed: 0", axis=1)

In [ ]:
whitewinedf1.head()

fixed.acidity  volatile.acidity  citric.acid  ...  alcohol  quality  New_Quality
0            7.0              0.27         0.36  ...      8.8        6        worst
1            6.3              0.30         0.34  ...      9.5        6        worst
2            8.1              0.28         0.40  ...     10.1        6        worst
3            7.2              0.23         0.32  ...      9.9        6        worst
4            7.2              0.23         0.32  ...      9.9        6        worst

[5 rows x 13 columns]

In [ ]:
whitewinedf2 = whitewinedf1.drop("quality", axis=1)

In [ ]:
whitewinedf2.head()

fixed.acidity  volatile.acidity  citric.acid  ...  sulphates  alcohol  New_Quality
0            7.0              0.27         0.36  ...       0.45      8.8        worst
1            6.3              0.30         0.34  ...       0.49      9.5        worst
2            8.1              0.28         0.40  ...       0.44     10.1        worst
3            7.2              0.23         0.32  ...       0.40      9.9        worst
4            7.2              0.23         0.32  ...       0.40      9.9        worst

[5 rows x 12 columns]

In [ ]:
whitewinedf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype   
---  ------                --------------  -----   
 0   fixed.acidity         4898 non-null   float64 
 1   volatile.acidity      4898 non-null   float64 
 2   citric.acid           4898 non-null   float64 
 3   residual.sugar        4898 non-null   float64 
 4   chlorides             4898 non-null   float64 
 5   free.sulfur.dioxide   4898 non-null   float64 
 6   total.sulfur.dioxide  4898 non-null   float64 
 7   density               4898 non-null   float64 
 8   pH                    4898 non-null   float64 
 9   sulphates             4898 non-null   float64 
 10  alcohol               4898 non-null   float64 
 11  New_Quality           4898 non-null   category
dtypes: category(1), float64(11)
memory usage: 425.9 KB


In [ ]:
coded_whitewinedf2 = whitewinedf2.replace({'New_Quality':{'worst':0, 'best':1}})
coded_whitewinedf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed.acidity         4898 non-null   float64
 1   volatile.acidity      4898 non-null   float64
 2   citric.acid           4898 non-null   float64
 3   residual.sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free.sulfur.dioxide   4898 non-null   float64
 6   total.sulfur.dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  New_Quality           4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [ ]:
coded_whitewinedf2.describe()

fixed.acidity  volatile.acidity  ...      alcohol  New_Quality
count    4898.000000       4898.000000  ...  4898.000000  4898.000000
mean        6.854788          0.278241  ...    10.514267     0.036750
std         0.843868          0.100795  ...     1.230621     0.188166
min         3.800000          0.080000  ...     8.000000     0.000000
25%         6.300000          0.210000  ...     9.500000     0.000000
50%         6.800000          0.260000  ...    10.400000     0.000000
75%         7.300000          0.320000  ...    11.400000     0.000000
max        14.200000          1.100000  ...    14.200000     1.000000

[8 rows x 12 columns]

In [ ]:
coded_whitewinedf2.isnull().sum()

fixed.acidity           0
volatile.acidity        0
citric.acid             0
residual.sugar          0
chlorides               0
free.sulfur.dioxide     0
total.sulfur.dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
New_Quality             0
dtype: int64

In [ ]:
x=coded_whitewinedf2.iloc[:,:-1].values
y=coded_whitewinedf2.iloc[:,-1].values

In [ ]:
print('Predictor Variable')
print(x)
print('Target Variable')
print(y)

Predictor Variable
[[ 7.    0.27  0.36 ...  3.    0.45  8.8 ]
 [ 6.3   0.3   0.34 ...  3.3   0.49  9.5 ]
 [ 8.1   0.28  0.4  ...  3.26  0.44 10.1 ]
 ...
 [ 6.5   0.24  0.19 ...  2.99  0.46  9.4 ]
 [ 5.5   0.29  0.3  ...  3.34  0.38 12.8 ]
 [ 6.    0.21  0.38 ...  3.26  0.32 11.8 ]]
Target Variable
[0 0 0 ... 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
print(x_train[:5])

[[6.80000e+00 3.30000e-01 2.80000e-01 1.20000e+00 3.20000e-02 3.80000e+01
  1.31000e+02 9.88900e-01 3.19000e+00 4.10000e-01 1.30000e+01]
 [8.60000e+00 2.00000e-01 4.20000e-01 1.50000e+00 4.10000e-02 3.50000e+01
  1.25000e+02 9.92500e-01 3.11000e+00 4.90000e-01 1.14000e+01]
 [5.60000e+00 2.70000e-01 3.70000e-01 9.00000e-01 2.50000e-02 1.10000e+01
  4.90000e+01 9.88450e-01 3.29000e+00 3.30000e-01 1.31000e+01]
 [6.40000e+00 1.80000e-01 4.80000e-01 1.80000e+01 5.40000e-02 5.60000e+01
  1.83000e+02 1.00038e+00 2.98000e+00 6.10000e-01 8.50000e+00]
 [6.40000e+00 1.80000e-01 3.10000e-01 1.60000e+00 4.90000e-02 3.60000e+01
  1.27000e+02 9.93400e-01 3.60000e+00 6.70000e-01 1.04000e+01]]


In [ ]:
print(y_train[:10])

[0 0 0 0 0 0 1 0 0 1]


In [ ]:
print(x_test[:5])

[[7.3000e+00 3.2000e-01 3.5000e-01 1.4000e+00 5.0000e-02 8.0000e+00
  1.6300e+02 9.9244e-01 3.2400e+00 4.2000e-01 1.0700e+01]
 [7.0000e+00 3.1000e-01 2.6000e-01 7.4000e+00 6.9000e-02 2.8000e+01
  1.6000e+02 9.9540e-01 3.1300e+00 4.6000e-01 9.8000e+00]
 [7.6000e+00 1.4000e-01 7.4000e-01 1.6000e+00 4.0000e-02 2.7000e+01
  1.0300e+02 9.9160e-01 3.0700e+00 4.0000e-01 1.0800e+01]
 [5.0000e+00 2.9000e-01 5.4000e-01 5.7000e+00 3.5000e-02 5.4000e+01
  1.5500e+02 9.8976e-01 3.2700e+00 3.4000e-01 1.2900e+01]
 [6.0000e+00 2.8000e-01 2.2000e-01 1.2150e+01 4.8000e-02 4.2000e+01
  1.6300e+02 9.9570e-01 3.2000e+00 4.6000e-01 1.0100e+01]]


In [ ]:
print(y_test[:10])

[0 0 0 1 0 0 0 0 0 0]


In [ ]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
Std_Scale = StandardScaler()
Std_Scale.fit(x_train)
std_x_train = Std_Scale.transform(x_train)

In [ ]:
print(Std_Scale.mean_)

[6.85931119e+00 2.78546148e-01 3.33008440e-01 6.33879662e+00
 4.58671386e-02 3.53053362e+01 1.38528859e+02 9.93995621e-01
 3.18810509e+00 4.90329431e-01 1.05209847e+01]


In [ ]:
print(std_x_train[:5])

[[-0.07184924  0.51219428 -0.44478469 -1.02861418 -0.62706538  0.15925577
  -0.17846952 -1.73684441  0.01257632 -0.69116914  2.01496586]
 [ 2.10866059 -0.7818829   0.72993119 -0.96856427 -0.22008968 -0.0180455
  -0.32069785 -0.50978294 -0.51837586 -0.00283448  0.71447154]
 [-1.52552246 -0.08507211  0.31038981 -1.08866409 -0.94360203 -1.43645563
  -2.12225677 -1.8902271   0.67626656 -1.3795038   2.09624675]
 [-0.55640698 -0.98097169  1.23338086  2.33418055  0.3677641   1.22306336
   1.05417605  2.17611828 -1.38117316  1.0296675  -1.64267443]
 [-0.55640698 -0.98097169 -0.19305986 -0.94854764  0.1416665   0.04105492
  -0.27328841 -0.20301757  2.73370628  1.5459185  -0.09833742]]


**Logistic** **Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
LogReg = LogisticRegression()
LogReg.fit(std_x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
std_x_test = Std_Scale.transform(x_test)

In [ ]:
print(std_x_test[:5])

[[ 0.53384793  0.41264988  0.14257325 -0.98858091  0.18688602 -1.6137569
   0.5800816  -0.53023397  0.34442144 -0.60512731  0.14550527]
 [ 0.17042963  0.31310548 -0.61260124  0.21241721  1.04605693 -0.43174845
   0.50896743  0.47868324 -0.38563781 -0.26095998 -0.58602279]
 [ 0.89726624 -1.37914929  3.41499607 -0.94854764 -0.2653092  -0.49084888
  -0.84220175 -0.81654831 -0.78385195 -0.77721097  0.22678616]
 [-2.25235907  0.11401668  1.73683052 -0.12786559 -0.49140681  1.10486252
   0.39044382 -1.44371306  0.54352851 -1.29346197  1.93368496]
 [-1.04096472  0.01447229 -0.94823435  1.16320739  0.09644697  0.39565745
   0.5800816   0.58093837  0.07894535 -0.26095998 -0.3421801 ]]


In [ ]:
y_pred = LogReg.predict(std_x_test)

In [ ]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [ ]:
from sklearn.metrics import confusion_matrix
conf_Mat_LogReg = confusion_matrix(y_test, y_pred)
conf_Mat_LogReg

array([[1156,   30],
       [  24,   15]])

In [ ]:
from sklearn.metrics import classification_report
Classif_Report_LogReg = classification_report(y_test, y_pred)
print(Classif_Report_LogReg)

              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1186
           1       0.33      0.38      0.36        39

    accuracy                           0.96      1225
   macro avg       0.66      0.68      0.67      1225
weighted avg       0.96      0.96      0.96      1225



In [ ]:
LogReg.coef_

array([[ 0.34009401, -0.15497951,  0.04470237,  1.09636842, -0.07428744,
         0.36811268, -0.11834066, -1.09124739,  0.45624927,  0.03196995,
         0.62673764]])

In [ ]:
LogReg.intercept_

array([-3.83017383])

**Desicion Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DecTree = DecisionTreeClassifier()
DecTree.fit(std_x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred = DecTree.predict(std_x_test)

In [ ]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [ ]:
print(y_test)

[0 0 0 ... 0 0 0]


In [ ]:
Conf_Mat_DecTree = confusion_matrix(y_test, y_pred)
Conf_Mat_DecTree

array([[1156,   30],
       [  24,   15]])

In [ ]:
Classif_Report_DecTree = classification_report(y_test, y_pred)
print(Classif_Report_DecTree)

              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1186
           1       0.33      0.38      0.36        39

    accuracy                           0.96      1225
   macro avg       0.66      0.68      0.67      1225
weighted avg       0.96      0.96      0.96      1225



In [ ]:
DecTree.tree_